name: Release
on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
          npm install @google/semantic-release-replace-plugin -D
          npm add @qiwi/semantic-release-gh-pages-plugin -D
          npm install @semantic-release/exec -D
      - name: Set up Python 3.10 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Enable bash scripts
        run: |
          chmod u+x ./upm-data/upm.sh
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release