name: Release
on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
          npm install @google/semantic-release-replace-plugin -D
      - name: Set up Python 3.10 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Checkout UPM branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: upm/release
          path: upm-package
      - name: Publish UPM
        run: |
            version=$(./.ci/jq '.version' upm-data/package.json)
            version=${version//\"/}

            (cd upm-package && git rm -r *)
            python ./upm-data/upm.py "prepare" "."
            (cd upm-package && git add .)
            (cd upm-package && git commit -m "chore(upm): publish upm/release v$version")
            (cd upm-package && git push origin upm/release)
        shell: bash
